### ISSUE TITLE
New sound.wav

### ISSUE THREAD

**Issue by WiiNoMa** [Disconnect24/dc24-channel-shortcut#1]
Here is a new sound.wav. (i don't think it counts as meme music) Rename the file type to .wav.
[sound.txt](https://github.com/Disconnect24/dc24-channel-shortcut/files/2697170/sound.txt)

**Comment by yeah-its-gloria** [comment]
1) Why didn't you make a **[Pull Request](https://github.com/Disconnect24/dc24-channel-shortcut/pulls)**?
2) Why did you name it `sound.txt`? 
3) Could you tell us what it is? *It's a part of the Mii Channel theme, I guess*

**Comment by WiiNoMa** [comment]
1. i was having problems making a pr
2. issues dont support .wav
3. so?

**Comment by Puppercino** [comment]
@WiiNoMa For your third point, Disconnect24 is obliged to follow DMCA and related laws. Not following these things can get us sued by Nintendo which is why we won't be accepting it. Sorry.
